app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/





Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware'=> 'auth.checkrole:admin', 'as' => 'admin.'] , function () {

    Route::get('categories',['as' => 'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::get('categories/delete/{id}',['as'=>'categories.delete','uses'=>'CategoriesController@delete']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);

    Route::get('clients',['as' => 'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);

    Route::get('products',['as' => 'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);

    Route::get('orders',['as' => 'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/create',['as'=>'orders.create','uses'=>'OrdersController@create']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::get('orders/destroy/{id}',['as'=>'orders.destroy','uses'=>'OrdersController@destroy']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);
    Route::post('orders/store',['as'=>'orders.store','uses'=>'OrdersController@store']);

    Route::get('cupoms',['as' => 'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::get('cupoms/edit/{id}',['as'=>'cupoms.edit','uses'=>'CupomsController@edit']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::post('cupoms/update/{id}',['as'=>'cupoms.update','uses'=>'CupomsController@update']);

});

Route::group(['prefix' => 'customer', 'middleware'=>'auth.checkrole:client', 'as' => 'customer.'], function(){
    Route::get('order',['as' => 'order.index','uses'=>'CheckoutController@index']);
    Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});


Route::group(['middleware' => 'cors'], function(){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix' => 'api', 'middleware'=> 'oauth', 'as' => 'api.'] , function () {

        Route::get('authenticated', 'Api\UserController@authenticated');

        Route::group(['prefix' => 'client', 'middleware'=>'oauth.checkrole:client','as' => 'client.'] , function () {
            Route::resource('order', 'Api\Client\ClientCheckoutController' ,['except' => ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix' => 'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as' => 'deliveryman'] , function () {
            Route::resource('order',
                'Api\Deliveryman\DeliverymanCheckoutController',[
                    'except' => ['create','edit','destroy','store']
                ]);
            Route::patch('order/{id}/update-status',[
                'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                'as' => 'orders.update_status'
            ]);
        });

        Route::get('cupom/{code}','Api\CupomController@show');
    });

});

app/Models/Client.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode',
    ];

    public function user()
    {
        return $this->hasOne(User::class,'id','user_id');
    }
}

app/Http/Controllers/Api/Client/ClientCheckoutController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Http\Requests\AdminClientRequest;
use CodeDelivery\Http\Requests\CheckoutRequest;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\OrderService;
use Illuminate\Http\Request;
use CodeDelivery\Http\Controllers\Controller;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;

class ClientCheckoutController extends Controller
{

    private $with = ['client', 'cupom' , 'items'];

    public function __construct(
        OrderRepository $repository,
        UserRepository $userRepository,
        OrderService $orderService
    )
    {
        $this->repository = $repository;
        $this->userRepository = $userRepository;
        $this->orderService = $orderService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Authorizer::getResourceOwnerId();

        $clientId = $this->userRepository->find($id)->client->id;

        $orders = $this->repository
            ->skipPresenter(false)
            ->with($this->with)->scopeQuery(function($query) use ($clientId) {
            return $query->where('client_id', '=', $clientId);
        })->paginate();

        return $orders;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CheckoutRequest $request)
    {
        $data = $request->all();
        $id = Authorizer::getResourceOwnerId();
        $clientId = $this->userRepository->find($id)->client->id;
        $data['client_id'] = $clientId;
        $o = $this->orderService->create($data);

        return $this->repository
            ->skipPresenter(false)
            ->with($this->with)
            ->find($o->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->repository
            ->skipPresenter(false)
            ->with($this->with)->find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/Client/ClientProductController.php
<?php

namespace CodeDelivery\Http\Controllers\Api\Client;

use CodeDelivery\Repositories\ProductRepository;
use CodeDelivery\Http\Controllers\Controller;


class ClientProductController extends Controller
{

    private $repository;

    public function __construct(ProductRepository $productRepository)
    {
        $this->repository = $productRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->repository->skipPresenter(false)->all();
        return $products;
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminClientRequest;
use CodeDelivery\Repositories\ClientRepository;
use CodeDelivery\Services\ClientService;


class ClientsController extends Controller
{
    private $clientRepository;
    /**
     * @var ClientService
     */
    private $clientService;

    public function __construct(ClientRepository $clientRepository, ClientService $clientService)
    {
        $this->clientRepository = $clientRepository;
        $this->clientService = $clientService;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = $this->clientRepository->paginate();
        return view('admin.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminClientRequest $request)
    {
        $this->clientService->create($request->all());
        return redirect()->route('admin.clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = $this->clientRepository->find($id);
        return view('admin.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminClientRequest $request, $id)
    {
        $this->clientService->update($request->all(), $id);
        return redirect()->route('admin.clients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/clients/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rothink
 * Date: 17/10/16
 * Time: 23:46
 */
?>
<div class="form-group">
    {!! Form::label('Name','Nome:') !!}
    {!! Form::text('user[name]',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Email','E-mail:') !!}
    {!! Form::text('user[email]',null,['class'=>'form-control']) !!}
</div>
{{--<div class="form-group">--}}
    {{--{!! Form::label('Password','Senha:') !!}--}}
    {{--{!! Form::password('user[password]',null,['class'=>'form-control']) !!}--}}
{{--</div>--}}
<div class="form-group">
    {!! Form::label('Phone','Telefone:') !!}
    {!! Form::text('phone',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Address','Endereço:') !!}
    {!! Form::text('address',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('City','Cidade:') !!}
    {!! Form::text('city',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('State','Estado:') !!}
    {!! Form::text('state',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Zipcode','Código postal:') !!}
    {!! Form::text('zipcode',null,['class'=>'form-control']) !!}
</div>

resources/views/admin/clients/create.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Novo Cliente</h3>
    <br>

    @include('errors._check')

    {!! Form::Open(['route' => 'admin.clients.store', 'class' => 'form']) !!}

        @include('admin.clients._form')

        <div class="form-group">

            {!! Form::submit('Criar Cliente',['class' => 'btn btn-success']) !!}
        </div>

    {!! Form::close() !!}
</div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Editando cliente: {{$client->user->name}}</h3>
    <br>
    @include('errors._check')

    {!! Form::model($client , ['route'=>['admin.clients.update', $client->id]]) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Alterar Cliente',['class' => 'btn btn-primary']) !!}
        </div>

    {!! Form::close() !!}
</div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Clients</h3>
    <br>
    <a href="{{route('admin.clients.create')}}" class="btn btn-default">Novo Cliente</a>
    <br><br>


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>Endereço</th>
            <th>Cidade</th>
            <th>Estado</th>
            <th>Zipcode</th>
            <th>Ações</th>
        </tr>
        </thead>

        <tbody>
        @foreach($clients as $client)
            <tr>
                <td>{{$client->id}}</td>
                <td>{{$client->user->name}}</td>
                <td>{{$client->user->email}}</td>
                <td>{{$client->phone}}</td>
                <td>{{$client->address}}</td>
                <td>{{$client->city}}</td>
                <td>{{$client->state}}</td>
                <td>{{$client->zipcode}}</td>
                <td>
                    <a href="{{route('admin.clients.edit', ['id' => $client->id])}}" class="btn btn-default">Editar</a>
                    <a href="{{route('admin.clients.destroy', ['id' => $client->id])}}" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $clients->render() !!}
    


    <ul>

    </ul>
</div>



@endsection