app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/





Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware'=> 'auth.checkrole:admin', 'as' => 'admin.'] , function () {

    Route::get('categories',['as' => 'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::get('categories/delete/{id}',['as'=>'categories.delete','uses'=>'CategoriesController@delete']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);

    Route::get('clients',['as' => 'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);

    Route::get('products',['as' => 'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);

    Route::get('orders',['as' => 'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/create',['as'=>'orders.create','uses'=>'OrdersController@create']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::get('orders/destroy/{id}',['as'=>'orders.destroy','uses'=>'OrdersController@destroy']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);
    Route::post('orders/store',['as'=>'orders.store','uses'=>'OrdersController@store']);

    Route::get('cupoms',['as' => 'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::get('cupoms/edit/{id}',['as'=>'cupoms.edit','uses'=>'CupomsController@edit']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::post('cupoms/update/{id}',['as'=>'cupoms.update','uses'=>'CupomsController@update']);

});

Route::group(['prefix' => 'customer', 'middleware'=>'auth.checkrole:client', 'as' => 'customer.'], function(){
    Route::get('order',['as' => 'order.index','uses'=>'CheckoutController@index']);
    Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});


Route::group(['middleware' => 'cors'], function(){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix' => 'api', 'middleware'=> 'oauth', 'as' => 'api.'] , function () {

        Route::get('authenticated', 'Api\UserController@authenticated');

        Route::group(['prefix' => 'client', 'middleware'=>'oauth.checkrole:client','as' => 'client.'] , function () {
            Route::resource('order', 'Api\Client\ClientCheckoutController' ,['except' => ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix' => 'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as' => 'deliveryman'] , function () {
            Route::resource('order',
                'Api\Deliveryman\DeliverymanCheckoutController',[
                    'except' => ['create','edit','destroy','store']
                ]);
            Route::patch('order/{id}/update-status',[
                'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                'as' => 'orders.update_status'
            ]);
        });

        Route::get('cupom/{code}','Api\CupomController@show');
    });

});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status',
        'cupom_id'
    ];

    public function transform()
    {
        return [
            'order' => $this->id,
            'items' => $this->items
        ];
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

}

app/Http/Controllers/OrdersController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Controllers\Controller;

class OrdersController extends Controller
{


    /**
     * @var OrderRepository
     */
    private $repository;

    public function __construct(OrderRepository $repository)
    {

        $this->repository = $repository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->repository->paginate();
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, UserRepository $userRepository)
    {

        $list_status = [0=> 'Pendente', 1=>'A caminho', 2 => 'Entregue', 3=> 'Cancelado'];

        $deliveryman = $userRepository->getDeliverymen();

        $order = $this->repository->find($id);
        return view('admin.orders.edit', compact('order','list_status', 'deliveryman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/order/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rothink
 * Date: 17/10/16
 * Time: 23:46
 */
?>
<div class="form-group">
{!! Form::label('Name','Nome:') !!}
{!! Form::text('name',null,['class'=>'form-control']) !!}
</div>

resources/views/customer/order/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo Pedido</h3>


        @include('errors._check')

        <div class="container">
            {!! Form::open(['route'=>'customer.order.store','class' => 'form']) !!}
                <div class="form-group">
                    <label>Total:</label>
                    <p id="total"></p>
                    <a href="#" id="btnNewItem" class="btn btn-default">Novo Item</a> <br/><br/>

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <select class="form-control" name="items[0][product_id]">
                                        @foreach($products as $p)
                                            <option value="{{$p->id}}" data-price="{{$p->price}}">{{$p->name}} -- {{$p->price}}</option>
                                        @endforeach
                                    </select>
                                </td>
                                <td>
                                    {!! Form::text('items[0][qtd]', 1, ['class' => 'form-control']) !!}
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
                <div class="form-group">
                    {!! Form::submit('Criar pedido', ['class'=>'btn btn-primary']) !!}
                </div>

            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('post-script')
    <script>

        $("#btnNewItem").click(function(){

            var row = $("table tbody > tr:last"),
                newRow = row.clone(),
                length = $("table tbody tr").length;

            newRow.find("td").each(function(){
                var td = $(this),
                    input = td.find("input,select"),
                    name = input.attr("name");

                input.attr("name", name.replace((length - 1) + "" , length + ""));
            });

            newRow.find("input").val(1);
            newRow.insertAfter(row);
            calculateTotal();

            $(document.body).on('click', 'select', function() {
                calculateTotal();
            });


            $(document.body).on('blur', 'input', function() {
                $('input[name*=qtd]').blur(function () {
                    calculateTotal();
                });
            });


            function calculateTotal() {
                var total = 0,
                    trLen = $('table tbody tr').length,
                    tr = null, price, qtd;
                for (var i = 0; i < trLen; i++) {
                    tr = $('table tbody tr').eq(i);
                    price = tr.find(':selected').data('price');
                    qtd = tr.find('input').val();
                    total += price * qtd;
                }

                $("#total").html(total);
            }
        });
    </script>
@endsection

resources/views/customer/order/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo Pedido</h3>

    <a href="{{route('customer.order.create')}}" class="btn btn-default">Novo pedido</a>
    <br><br>

        <table class="table table-bordered">
            <thead>
                <tr>ID</tr>
                <tr>Total</tr>
                <tr>Status</tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>{{$order->id}}</td>
                    <td>{{$order->total}}</td>
                    <td>{{$order->status}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    {!! $orders->render() !!}
@endsection