app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/





Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware'=> 'auth.checkrole:admin', 'as' => 'admin.'] , function () {

    Route::get('categories',['as' => 'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::get('categories/delete/{id}',['as'=>'categories.delete','uses'=>'CategoriesController@delete']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);

    Route::get('clients',['as' => 'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);

    Route::get('products',['as' => 'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);

    Route::get('orders',['as' => 'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/create',['as'=>'orders.create','uses'=>'OrdersController@create']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::get('orders/destroy/{id}',['as'=>'orders.destroy','uses'=>'OrdersController@destroy']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);
    Route::post('orders/store',['as'=>'orders.store','uses'=>'OrdersController@store']);

    Route::get('cupoms',['as' => 'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::get('cupoms/edit/{id}',['as'=>'cupoms.edit','uses'=>'CupomsController@edit']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::post('cupoms/update/{id}',['as'=>'cupoms.update','uses'=>'CupomsController@update']);

});

Route::group(['prefix' => 'customer', 'middleware'=>'auth.checkrole:client', 'as' => 'customer.'], function(){
    Route::get('order',['as' => 'order.index','uses'=>'CheckoutController@index']);
    Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});


Route::group(['middleware' => 'cors'], function(){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix' => 'api', 'middleware'=> 'oauth', 'as' => 'api.'] , function () {

        Route::get('authenticated', 'Api\UserController@authenticated');

        Route::group(['prefix' => 'client', 'middleware'=>'oauth.checkrole:client','as' => 'client.'] , function () {
            Route::resource('order', 'Api\Client\ClientCheckoutController' ,['except' => ['create','edit','destroy']]);
            Route::get('products','Api\Client\ClientProductController@index');
        });

        Route::group(['prefix' => 'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as' => 'deliveryman'] , function () {
            Route::resource('order',
                'Api\Deliveryman\DeliverymanCheckoutController',[
                    'except' => ['create','edit','destroy','store']
                ]);
            Route::patch('order/{id}/update-status',[
                'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                'as' => 'orders.update_status'
            ]);
        });

        Route::get('cupom/{code}','Api\CupomController@show');
    });

});

app/Models/Category.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Category extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'name'
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminCategoryRequest;
use CodeDelivery\Repositories\CategoryRepository;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $repository;

    public function __construct(CategoryRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $categories = $this->repository->paginate();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(AdminCategoryRequest $request)
    {
        $this->repository->create($request->all());
        return redirect()->route('admin.categories.index');
    }

    public function edit($id)
    {
        $category = $this->repository->find($id);
        return view('admin.categories.edit',compact('category'));
    }

    public function update(AdminCategoryRequest $request, $id)
    {
        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/_form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rothink
 * Date: 17/10/16
 * Time: 23:46
 */
?>
<div class="form-group">
{!! Form::label('Name','Nome:') !!}
{!! Form::text('name',null,['class'=>'form-control']) !!}
</div>

resources/views/admin/categories/create.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Nova Categoria</h3>
    <br>

    @include('errors._check')

    {!! Form::Open(['route' => 'admin.categories.store', 'class' => 'form']) !!}

        @include('admin.categories._form')

        <div class="form-group">

            {!! Form::submit('Criar categoria',['class' => 'btn btn-primary']) !!}
        </div>

    {!! Form::close() !!}
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Editando Categoria {{$category->name}}</h3>
    <br>
    @include('errors._check')
    {!! Form::model($category , ['route'=>['admin.categories.update', $category->id]]) !!}

        @include('admin.categories._form')
        <div class="form-group">
            {!! Form::submit('Alterar categoria',['class' => 'btn btn-primary']) !!}
        </div>

    {!! Form::close() !!}
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Categorias</h3>
    <br>
    <a href="{{route('admin.categories.create')}}" class="btn btn-default">Nova Categoria</a>
    <br><br>


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
        </thead>

        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td>
                    <a href="{{route('admin.categories.edit', ['id' => $category->id])}}" class="btn btn-default">Editar</a>
                    <a href="{{route('admin.categories.delete', ['id' => $category->id])}}" class="btn btn-danger">Excluir</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {!! $categories->render() !!}
    


    <ul>

    </ul>
</div>



@endsection